In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,5,"jalpa", 6+6j])

array(['1', '2', '3', '4', '5', 'jalpa', '(6+6j)'], dtype='<U64')

In [6]:
np.array([1,2,3,45,6,0.8])

array([ 1. ,  2. ,  3. , 45. ,  6. ,  0.8])

In [7]:
np.array([[1,4],[4,5]])

array([[1, 4],
       [4, 5]])

In [8]:
np.array([[1,4],[4,5],[6,7]])

array([[1, 4],
       [4, 5],
       [6, 7]])

In [9]:
np.array([[1,4],[4,5,6]])

C:\Users\Jalpa\AppData\Local\Temp/ipykernel_3728/3075439275.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,4],[4,5,6]])


array([list([1, 4]), list([4, 5, 6])], dtype=object)

In [10]:
np.array([[[1,4],[4,5]]])

array([[[1, 4],
        [4, 5]]])

In [11]:
np.array([1,2,3], ndmin = 3)

array([[[1, 2, 3]]])

In [12]:
type(np.array([1,2,3], ndmin = 3))

numpy.ndarray

In [13]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
np.array([1,2,3], dtype = int)

array([1, 2, 3])

In [15]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [16]:
arr = np.array([(1,2),(3,4)], dtype=[('a','<i2'), (('b','<i8'))])

In [17]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [18]:
type(arr[1][1])

numpy.int64

In [19]:
arr = np.array([(1,2),(3,4)])

In [20]:
arr

array([[1, 2],
       [3, 4]])

In [21]:
arr[0]

array([1, 2])

In [23]:
type(arr[0][1])

numpy.int32

In [24]:
np.mat(arr)

matrix([[1, 2],
        [3, 4]])

In [25]:
l = [3,4,5,6,7]

In [27]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [28]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [29]:
np.array(l)

array([3, 4, 5, 6, 7])

In [30]:
np.asanyarray(mat)

NameError: name 'mat' is not defined

In [31]:
np.asarray(mat)

NameError: name 'mat' is not defined

In [33]:
issubclass(np.matrix , np.asarray)

TypeError: issubclass() arg 2 must be a class or tuple of classes

In [34]:
arr 

array([[1, 2],
       [3, 4]])

In [35]:
a = arr

In [36]:
b = np.copy(arr)

In [37]:
b

array([[1, 2],
       [3, 4]])

In [38]:
arr[0][0] = 67

In [39]:
a

array([[67,  2],
       [ 3,  4]])

In [40]:
b

array([[1, 2],
       [3, 4]])

In [42]:
arr[0:10]

array([[67,  2],
       [ 3,  4]])

In [43]:
arr[-1]

array([3, 4])

In [44]:
for i in arr:
    print(i)

[67  2]
[3 4]


In [45]:
np.fromfunction(lambda i, j :i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [46]:
np.fromfunction(lambda i, j :i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [47]:
np.fromfunction(lambda i, j :i/j, (3,3))

C:\Users\Jalpa\AppData\Local\Temp/ipykernel_3728/955454589.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j :i/j, (3,3))
C:\Users\Jalpa\AppData\Local\Temp/ipykernel_3728/955454589.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j :i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [50]:
[i*i for i in range(5)]
    

[0, 1, 4, 9, 16]

In [51]:
(i*i for i in range(5))

<generator object <genexpr> at 0x000001DA81434F90>

In [52]:
def test(x):
    yield x
    

In [55]:
gen = test(3)

In [57]:
np.fromiter(range(5) , dtype = int)

array([0, 1, 2, 3, 4])

In [58]:
np.fromstring('1,2,3,4', sep = ',', dtype = int)

array([1, 2, 3, 4])

In [59]:
np.fromstring('1,2,3,4', sep = ',', dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [60]:
np.fromstring('1,2,3,4', sep = ',')

array([1., 2., 3., 4.])

In [61]:
l = [2,3,4,5,6]

In [62]:
arr = np.array(l)

In [63]:
arr

array([2, 3, 4, 5, 6])

In [66]:
l1 = [[1,2,3,4], [1,3,4,5], [5,6,7,8]]

In [68]:
arr1 = np.array(l1)

In [69]:
arr1

array([[1, 2, 3, 4],
       [1, 3, 4, 5],
       [5, 6, 7, 8]])

In [70]:
type(arr)

numpy.ndarray

In [71]:
arr1.ndim

2

In [72]:
arr1.size

12

In [73]:
arr1.shape

(3, 4)

In [74]:
arr1.dtype

dtype('int32')

In [75]:
arr.size

5

In [76]:
arr2 = np.array([[[1,2,3],[1,2,3]]])

In [77]:
arr2

array([[[1, 2, 3],
        [1, 2, 3]]])

In [79]:
arr2.dtype

dtype('int32')

In [80]:
arr2.size

6

In [81]:
arr2.ndim

3

In [82]:
arr2.shape

(1, 2, 3)

In [85]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [87]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [88]:
np.arange(6.6,8,0.2)

array([6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. ])

In [89]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [92]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [93]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [94]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [97]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [98]:
np.ones(3)

array([1., 1., 1.])

In [99]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [103]:
np.ones((2,3,2))+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [104]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [106]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [109]:
np.linspace(2,4,4, endpoint =False, axis = 0)

array([2. , 2.5, 3. , 3.5])

In [112]:
np.logspace([2,3],4)

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [113]:
np.logspace([2],[3],4,axis=0)

array([[ 100.        ],
       [ 215.443469  ],
       [ 464.15888336],
       [1000.        ]])

In [114]:
d = np.linspace(4,5,40)

In [115]:
d

array([4.        , 4.02564103, 4.05128205, 4.07692308, 4.1025641 ,
       4.12820513, 4.15384615, 4.17948718, 4.20512821, 4.23076923,
       4.25641026, 4.28205128, 4.30769231, 4.33333333, 4.35897436,
       4.38461538, 4.41025641, 4.43589744, 4.46153846, 4.48717949,
       4.51282051, 4.53846154, 4.56410256, 4.58974359, 4.61538462,
       4.64102564, 4.66666667, 4.69230769, 4.71794872, 4.74358974,
       4.76923077, 4.79487179, 4.82051282, 4.84615385, 4.87179487,
       4.8974359 , 4.92307692, 4.94871795, 4.97435897, 5.        ])

In [116]:
d.shape

(40,)

In [117]:
d.reshape(40,1)

array([[4.        ],
       [4.02564103],
       [4.05128205],
       [4.07692308],
       [4.1025641 ],
       [4.12820513],
       [4.15384615],
       [4.17948718],
       [4.20512821],
       [4.23076923],
       [4.25641026],
       [4.28205128],
       [4.30769231],
       [4.33333333],
       [4.35897436],
       [4.38461538],
       [4.41025641],
       [4.43589744],
       [4.46153846],
       [4.48717949],
       [4.51282051],
       [4.53846154],
       [4.56410256],
       [4.58974359],
       [4.61538462],
       [4.64102564],
       [4.66666667],
       [4.69230769],
       [4.71794872],
       [4.74358974],
       [4.76923077],
       [4.79487179],
       [4.82051282],
       [4.84615385],
       [4.87179487],
       [4.8974359 ],
       [4.92307692],
       [4.94871795],
       [4.97435897],
       [5.        ]])

In [118]:
d.reshape(1,2,20)

array([[[4.        , 4.02564103, 4.05128205, 4.07692308, 4.1025641 ,
         4.12820513, 4.15384615, 4.17948718, 4.20512821, 4.23076923,
         4.25641026, 4.28205128, 4.30769231, 4.33333333, 4.35897436,
         4.38461538, 4.41025641, 4.43589744, 4.46153846, 4.48717949],
        [4.51282051, 4.53846154, 4.56410256, 4.58974359, 4.61538462,
         4.64102564, 4.66666667, 4.69230769, 4.71794872, 4.74358974,
         4.76923077, 4.79487179, 4.82051282, 4.84615385, 4.87179487,
         4.8974359 , 4.92307692, 4.94871795, 4.97435897, 5.        ]]])

In [119]:
d.reshape(2,1,20)

array([[[4.        , 4.02564103, 4.05128205, 4.07692308, 4.1025641 ,
         4.12820513, 4.15384615, 4.17948718, 4.20512821, 4.23076923,
         4.25641026, 4.28205128, 4.30769231, 4.33333333, 4.35897436,
         4.38461538, 4.41025641, 4.43589744, 4.46153846, 4.48717949]],

       [[4.51282051, 4.53846154, 4.56410256, 4.58974359, 4.61538462,
         4.64102564, 4.66666667, 4.69230769, 4.71794872, 4.74358974,
         4.76923077, 4.79487179, 4.82051282, 4.84615385, 4.87179487,
         4.8974359 , 4.92307692, 4.94871795, 4.97435897, 5.        ]]])

In [121]:
np.random.rand(3)

array([0.59432869, 0.85392002, 0.44965682])

In [122]:
np.random.rand(5,4)

array([[0.52649383, 0.42045926, 0.4756407 , 0.78225313],
       [0.90480617, 0.87144844, 0.80120492, 0.43919193],
       [0.3135565 , 0.8181114 , 0.38097062, 0.00457337],
       [0.93868374, 0.18654198, 0.74430519, 0.65393376],
       [0.30721348, 0.26356328, 0.54238954, 0.62100558]])

In [123]:
np.random.rand(2,2,3)

array([[[0.83390487, 0.98163769, 0.69974883],
        [0.89069729, 0.14678394, 0.95755187]],

       [[0.57930232, 0.00974273, 0.1054832 ],
        [0.17990086, 0.12142374, 0.98492149]]])

In [124]:
np.random.randint(5)

2

In [128]:
np.random.randint((5,6),40)

array([25, 23])

In [126]:
np.random.randint(5,6,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [127]:
np.random.randn(4,4)

array([[-1.47990378, -1.12733996, -1.01484769,  0.16744165],
       [-0.15005387, -0.40625876,  0.36255388,  1.45587195],
       [-1.19580203,  1.24231766, -1.19293718, -0.79463345],
       [ 0.09867357,  1.09089099,  0.4001364 , -0.41590676]])

In [129]:
arr = np.random.randint(3,9,(3,3))

In [130]:
arr

array([[7, 6, 8],
       [6, 6, 6],
       [8, 6, 3]])

In [131]:
arr.reshape(1,1,9)

array([[[7, 6, 8, 6, 6, 6, 8, 6, 3]]])

In [132]:
arr.reshape(3,3,1)

array([[[7],
        [6],
        [8]],

       [[6],
        [6],
        [6]],

       [[8],
        [6],
        [3]]])

In [135]:
arr.reshape(3,-1)

array([[7, 6, 8],
       [6, 6, 6],
       [8, 6, 3]])

In [137]:
arr.reshape(3,-9898)

array([[7, 6, 8],
       [6, 6, 6],
       [8, 6, 3]])

In [138]:
arr.max()

8

In [139]:
arr.min()

3

In [143]:
arr = np.random.randint(4,100,(5,5))

In [144]:
arr

array([[18, 77, 94, 68, 52],
       [50, 26, 42,  9, 46],
       [30, 56, 45, 45, 59],
       [73, 49, 84, 87, 72],
       [ 8, 66, 40, 87, 89]])

In [147]:
arr[3: , 3:]       

array([[87, 72],
       [87, 89]])

In [151]:
arr[:,[1,3]]

array([[77, 68],
       [26,  9],
       [56, 45],
       [49, 87],
       [66, 87]])

In [152]:
arr

array([[18, 77, 94, 68, 52],
       [50, 26, 42,  9, 46],
       [30, 56, 45, 45, 59],
       [73, 49, 84, 87, 72],
       [ 8, 66, 40, 87, 89]])

In [153]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [154]:
arr[arr>10]

array([18, 77, 94, 68, 52, 50, 26, 42, 46, 30, 56, 45, 45, 59, 73, 49, 84,
       87, 72, 66, 40, 87, 89])

In [155]:
arr

array([[18, 77, 94, 68, 52],
       [50, 26, 42,  9, 46],
       [30, 56, 45, 45, 59],
       [73, 49, 84, 87, 72],
       [ 8, 66, 40, 87, 89]])

In [156]:
arr*arr

array([[ 324, 5929, 8836, 4624, 2704],
       [2500,  676, 1764,   81, 2116],
       [ 900, 3136, 2025, 2025, 3481],
       [5329, 2401, 7056, 7569, 5184],
       [  64, 4356, 1600, 7569, 7921]])

In [157]:
arr1 = np.random.randint(2,3,(2,2))

In [158]:
arr2 = np.random.randint(2,3,(2,2))

In [159]:
arr1

array([[2, 2],
       [2, 2]])

In [162]:
arr2

array([[2, 2],
       [2, 2]])

In [163]:
arr1*arr2

array([[4, 4],
       [4, 4]])

In [164]:
arr1@arr2

array([[8, 8],
       [8, 8]])

In [165]:
arr**2

array([[ 324, 5929, 8836, 4624, 2704],
       [2500,  676, 1764,   81, 2116],
       [ 900, 3136, 2025, 2025, 3481],
       [5329, 2401, 7056, 7569, 5184],
       [  64, 4356, 1600, 7569, 7921]], dtype=int32)

In [166]:
arr/0

C:\Users\Jalpa\AppData\Local\Temp/ipykernel_3728/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [171]:
arr = np.zeros((3,4))

In [172]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [173]:
a = np.array([1,2,3,4])

In [169]:
a

array([1, 2, 3, 4])

In [178]:
r= a.T
r

array([1, 2, 3, 4])

In [179]:
arr = np.random.rand(5,4)

In [180]:
arr

array([[0.93412405, 0.25922911, 0.5394683 , 0.00141069],
       [0.16925951, 0.05446102, 0.83030042, 0.64739383],
       [0.63792049, 0.67858919, 0.91405187, 0.43597265],
       [0.51616124, 0.51728337, 0.86068897, 0.29391959],
       [0.11037934, 0.97975103, 0.78754036, 0.26588813]])

In [181]:
np.exp(arr)

array([[2.54498321, 1.29593068, 1.7150947 , 1.00141169],
       [1.18442747, 1.05597131, 2.2940078 , 1.9105551 ],
       [1.89254122, 1.97109493, 2.49440911, 1.54646651],
       [1.67558313, 1.6774644 , 2.3647894 , 1.34167602],
       [1.1167016 , 2.66379295, 2.19798352, 1.30458911]])

In [182]:
arr1 = np.random.randint(2,5,(5,5))

In [183]:
arr1

array([[2, 4, 4, 3, 4],
       [4, 2, 2, 4, 3],
       [4, 2, 3, 3, 4],
       [4, 3, 2, 3, 2],
       [2, 4, 4, 3, 3]])

In [184]:
np.log(arr1)

array([[0.69314718, 1.38629436, 1.38629436, 1.09861229, 1.38629436],
       [1.38629436, 0.69314718, 0.69314718, 1.38629436, 1.09861229],
       [1.38629436, 0.69314718, 1.09861229, 1.09861229, 1.38629436],
       [1.38629436, 1.09861229, 0.69314718, 1.09861229, 0.69314718],
       [0.69314718, 1.38629436, 1.38629436, 1.09861229, 1.09861229]])

In [185]:
np.random.seed(13)

In [186]:
np.random.rand(3,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651],
       [0.64161334, 0.72201823, 0.03503652, 0.29844947]])

In [195]:
np.random.seed(13)
np.random.rand(3,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651],
       [0.64161334, 0.72201823, 0.03503652, 0.29844947]])

In [197]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])

In [191]:
a