In [1]:
import pandas as pd

In [2]:
import pandas as np

In [9]:
df = pd.DataFrame({
    'col1' : [1,2,3,4,5],
    'col2':[45,56,67,34,34],
    'col3':"jalpa ineuron one tech im".split()
})

In [10]:
df

col1  col2     col3
0     1    45    jalpa
1     2    56  ineuron
2     3    67      one
3     4    34     tech
4     5    34       im

In [5]:
"jalpa ineuron one".split()

['jalpa', 'ineuron', 'one']

In [6]:
df

col1  col2               col3
0     1    45  jalpa ineuron one
1     2    56  jalpa ineuron one
2     3    67  jalpa ineuron one
3     4    34  jalpa ineuron one
4     5    34  jalpa ineuron one

In [11]:
df['col4'] = df['col1']**2

In [12]:
df['col4']

0     1
1     4
2     9
3    16
4    25
Name: col4, dtype: int64

In [13]:
df

col1  col2     col3  col4
0     1    45    jalpa     1
1     2    56  ineuron     4
2     3    67      one     9
3     4    34     tech    16
4     5    34       im    25

In [14]:
df['col5'] = df['col3'].str[0]

In [15]:
df

col1  col2     col3  col4 col5
0     1    45    jalpa     1    j
1     2    56  ineuron     4    i
2     3    67      one     9    o
3     4    34     tech    16    t
4     5    34       im    25    i

In [17]:
def test(a):
    return a**2

In [18]:
test(2)

4

In [19]:
df['col4_4'] = df['col1'].apply(test)

In [20]:
df

col1  col2     col3  col4 col5  col4_4
0     1    45    jalpa     1    j       1
1     2    56  ineuron     4    i       4
2     3    67      one     9    o       9
3     4    34     tech    16    t      16
4     5    34       im    25    i      25

In [26]:
def test1(a):
    if a == 'j':
        return 'j'
    else:
        return 'z'

In [27]:
df['col6'] = df['col5'].apply(test1)

In [28]:
df

col1  col2     col3  col4 col5  col4_4 col6
0     1    45    jalpa     1    j       1    j
1     2    56  ineuron     4    i       4    z
2     3    67      one     9    o       9    z
3     4    34     tech    16    t      16    z
4     5    34       im    25    i      25    z

In [29]:
df['col6_6'] = df['col5'].apply(lambda a : 's' if a== 's' else 'z')

In [30]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6
0     1    45    jalpa     1    j       1    j      z
1     2    56  ineuron     4    i       4    z      z
2     3    67      one     9    o       9    z      z
3     4    34     tech    16    t      16    z      z
4     5    34       im    25    i      25    z      z

In [32]:
df['col_7'] = df['col3'].apply(len)

In [33]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6  col_7
0     1    45    jalpa     1    j       1    j      z      5
1     2    56  ineuron     4    i       4    z      z      7
2     3    67      one     9    o       9    z      z      3
3     4    34     tech    16    t      16    z      z      4
4     5    34       im    25    i      25    z      z      2

In [36]:
import math

In [39]:
df['col_8'] = df['col2'].apply(math.log)

In [40]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6  col_7     col_8
0     1    45    jalpa     1    j       1    j      z      5  3.806662
1     2    56  ineuron     4    i       4    z      z      7  4.025352
2     3    67      one     9    o       9    z      z      3  4.204693
3     4    34     tech    16    t      16    z      z      4  3.526361
4     5    34       im    25    i      25    z      z      2  3.526361

In [41]:
import numpy as np

In [42]:
l = [1,2,3,4]

In [43]:
type(l)

list

In [44]:
np.array(l)

array([1, 2, 3, 4])

In [45]:
type(np.array(l))

numpy.ndarray

In [52]:
a1 = np.array([3,4,5,6,3.0])

In [49]:
a = np.array([[1,2],[3,4]])

In [50]:
a

array([[1, 2],
       [3, 4]])

In [51]:
a[(1,1)]

4

In [53]:
a1

array([3., 4., 5., 6., 3.])

In [54]:
a1[2]

5.0

In [58]:
np.array([1,2,3,4],ndmin = 3)

array([[[1, 2, 3, 4]]])

In [62]:
np.asarray([1,23,4,5])

array([ 1, 23,  4,  5])

In [60]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [61]:
np.mat([1,2,3,3])

matrix([[1, 2, 3, 3]])

In [64]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [65]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [66]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [67]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [68]:
np.fromfunction(lambda i , j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [70]:
np.fromfunction(lambda i , j: i**j, (4,4), dtype = int)

array([[ 1,  0,  0,  0],
       [ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27]], dtype=int32)

In [71]:
np.mat(np.fromfunction(lambda i , j: i**j, (4,4), dtype = int))

matrix([[ 1,  0,  0,  0],
        [ 1,  1,  1,  1],
        [ 1,  2,  4,  8],
        [ 1,  3,  9, 27]], dtype=int32)

In [73]:
np.fromfunction(lambda i , j, z: i*j*z, (4,3,2),dtype = int) # three matrixes as a dimension of (3,2)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [80]:
a=np.fromfunction(lambda i , j, z, d: i*j*z*d, (4,3,2,2),dtype = int)

In [76]:
np.random.rand(100,4)

array([[0.31692802, 0.44275149, 0.89508001, 0.38416744],
       [0.55294397, 0.88520878, 0.06331632, 0.05271949],
       [0.98956506, 0.896287  , 0.61089053, 0.11751208],
       [0.01796661, 0.54730744, 0.094642  , 0.87237948],
       [0.74568104, 0.98376969, 0.76237486, 0.02658077],
       [0.36990212, 0.27604947, 0.85893684, 0.3563189 ],
       [0.98155713, 0.44642018, 0.51231296, 0.11092856],
       [0.16920116, 0.27475453, 0.7231593 , 0.17656265],
       [0.5186459 , 0.15116717, 0.78424731, 0.51409039],
       [0.64840519, 0.11903303, 0.85536335, 0.14085022],
       [0.99459442, 0.99516817, 0.57096057, 0.36062031],
       [0.6631389 , 0.72180497, 0.99675029, 0.47363135],
       [0.94246902, 0.17921384, 0.26557852, 0.08395097],
       [0.80787366, 0.96524945, 0.35535329, 0.89871266],
       [0.7925545 , 0.07249059, 0.07341803, 0.32478289],
       [0.41776591, 0.85274632, 0.38294811, 0.52049267],
       [0.25560288, 0.96049333, 0.87945813, 0.54957082],
       [0.21150443, 0.89543083,

In [77]:
np.random.randint(4,50)

8

In [78]:
np.random.randn(4,5)

array([[ 0.12626057, -0.63491158,  0.61191371,  1.32186571, -0.22906826],
       [ 0.12786145,  2.23243581,  0.9278023 , -0.91305049,  1.54552947],
       [-0.70500354,  0.77977123,  0.55557874,  1.90156373, -1.00153933],
       [ 0.60877857,  0.08030062, -0.58240312, -0.62479677,  0.52346557]])

In [79]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.351473  1.523768  0.432357 -0.638787  1.374261
1 -0.962125  0.392872  0.183973  1.586318 -0.035486
2  0.587642 -2.085147 -0.819532 -0.755066  1.029830
3 -1.058371  0.339291  1.318349  1.159974  1.180579

In [81]:
a

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [84]:
a.reshape(12,4,-234)

array([[[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [1]],

       [[0],
        [0],
        [0],
        [2]],

       [[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [2]],

       [[0],
        [0],
        [0],
        [4]],

       [[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [3]],

       [[0],
        [0],
        [0],
        [6]]])