In [3]:
import numpy as np
import pandas as pd

In [7]:
array = np.arange(0,20).reshape(5,4)

In [8]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
df= pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=["Row1", "Row2", "Row3", "Row4", "Row5"], 
             columns = ["Column1","Column2", "Columns3","Columns4"])

In [12]:
df.head()

Column1  Column2  Columns3  Columns4
Row1        0        1         2         3
Row2        4        5         6         7
Row3        8        9        10        11
Row4       12       13        14        15
Row5       16       17        18        19

In [13]:
df.tail(2)

Column1  Column2  Columns3  Columns4
Row4       12       13        14        15
Row5       16       17        18        19

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Column1   5 non-null      int32
 1   Column2   5 non-null      int32
 2   Columns3  5 non-null      int32
 3   Columns4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [16]:
df.describe()

Column1    Column2   Columns3   Columns4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [17]:
# Indexing
## Columns name, rowindex [loc], columnindex number [.iloc]

In [21]:
df[['Column1','Column2','Columns3']]

Column1  Column2  Columns3
Row1        0        1         2
Row2        4        5         6
Row3        8        9        10
Row4       12       13        14
Row5       16       17        18

In [22]:
# By using column name
type(df['Column1'])

pandas.core.series.Series

In [23]:
# In pandas multiple row and column comnination called Data frames

In [24]:
df.loc["Row2"]

Column1     4
Column2     5
Columns3    6
Columns4    7
Name: Row2, dtype: int32

In [29]:
df.iloc[2:4,0:2] # indexing technique for row and column

Column1  Column2
Row3        8        9
Row4       12       13

In [30]:
df.iloc[2:,1:]

Column2  Columns3  Columns4
Row3        9        10        11
Row4       13        14        15
Row5       17        18        19

In [32]:
## Convert data drame into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [33]:
## Basic Operations
df.isnull().sum()


Column1     0
Column2     0
Columns3    0
Columns4    0
dtype: int64

In [34]:
df.isnull()

Column1  Column2  Columns3  Columns4
Row1    False    False     False     False
Row2    False    False     False     False
Row3    False    False     False     False
Row4    False    False     False     False
Row5    False    False     False     False

In [35]:
df['Columns3'].value_counts()

2     1
6     1
10    1
14    1
18    1
Name: Columns3, dtype: int64

In [36]:
df['Columns3'].unique()

array([ 2,  6, 10, 14, 18])

In [37]:
df>4

Column1  Column2  Columns3  Columns4
Row1    False    False     False     False
Row2    False     True      True      True
Row3     True     True      True      True
Row4     True     True      True      True
Row5     True     True      True      True

In [39]:
df[df['Column2']>4] # conditional indexing

Column1  Column2  Columns3  Columns4
Row2        4        5         6         7
Row3        8        9        10        11
Row4       12       13        14        15
Row5       16       17        18        19

# String io pandas read_csv

In [40]:
from io import StringIO

In [41]:
df=pd.read_csv(r'https://raw.githubusercontent.com/subhadipml/Mercedes-Benz-Greener-Manufacturing/master/test.csv')

In [42]:
df

ID  X0  X1  X2 X3 X4  X5 X6 X8  X10  ...  X375  X376  X377  X378  \
0        1  az   v   n  f  d   t  a  w    0  ...     0     0     0     1   
1        2   t   b  ai  a  d   b  g  y    0  ...     0     0     1     0   
2        3  az   v  as  f  d   a  j  j    0  ...     0     0     0     1   
3        4  az   l   n  f  d   z  l  n    0  ...     0     0     0     1   
4        5   w   s  as  c  d   y  i  m    0  ...     1     0     0     0   
...    ...  ..  ..  .. .. ..  .. .. ..  ...  ...   ...   ...   ...   ...   
4204  8410  aj   h  as  f  d  aa  j  e    0  ...     0     0     0     0   
4205  8411   t  aa  ai  d  d  aa  j  y    0  ...     0     1     0     0   
4206  8413   y   v  as  f  d  aa  d  w    0  ...     0     0     0     0   
4207  8414  ak   v  as  a  d  aa  c  q    0  ...     0     0     1     0   
4208  8416   t  aa  ai  c  d  aa  g  r    0  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     0     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 377 columns]

In [43]:
type(df)

pandas.core.frame.DataFrame

In [47]:
data=('col1,col2,col3\n'
     'x,y,1\n'
     'a,b,2\n'
     'c,d,3')

In [48]:
data

'col1,col2,col3\nx,y,1\na,b,2\nc,d,3'

In [49]:
type(data)

str

In [50]:
StringIO(data) ## in memmory file format object

In [51]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [52]:
pd.read_csv(StringIO(data),usecols=['col1','col2'])

col1 col2
0    x    y
1    a    b
2    c    d

In [53]:
df.to_csv('test.csv')

In [ ]:
pd.read_csv('url',sep='\t') ## url file to csv converter

# read json (read_json)
# To Json (to_json)
# Json Normalize 

In [63]:
data = { "office": {
    "medical": [
      { "room-number": 100,
        "use": "reception",
        "sq-ft": 50,
        "price": 75
      },
      { "room-number": 101,
        "use": "waiting",
        "sq-ft": 250,
        "price": 75
      },
      { "room-number": 102,
        "use": "examination",
        "sq-ft": 125,
        "price": 150
      },
      { "room-number": 103,
        "use": "examination",
        "sq-ft": 125,
        "price": 150
      },
      { "room-number": 104,
        "use": "office",
        "sq-ft": 150,
        "price": 100
      }
    ],
    "parking": {
      "location": "premium",
      "style": "covered",
      "price": 750
    }
  }
}

In [60]:
data

{'office': {'medical': [{'room-number': 100,
    'use': 'reception',
    'sq-ft': 50,
    'price': 75},
   {'room-number': 101, 'use': 'waiting', 'sq-ft': 250, 'price': 75},
   {'room-number': 102, 'use': 'examination', 'sq-ft': 125, 'price': 150},
   {'room-number': 103, 'use': 'examination', 'sq-ft': 125, 'price': 150},
   {'room-number': 104, 'use': 'office', 'sq-ft': 150, 'price': 100}],
  'parking': {'location': 'premium', 'style': 'covered', 'price': 750}}}

In [61]:
type(data)

dict

In [64]:
data1 = [{ "office": {
    "medical": [
      { "room-number": 100,
        "use": "reception",
        "sq-ft": 50,
        "price": 75
      },
      { "room-number": 101,
        "use": "waiting",
        "sq-ft": 250,
        "price": 75
      },
      { "room-number": 102,
        "use": "examination",
        "sq-ft": 125,
        "price": 150
      },
      { "room-number": 103,
        "use": "examination",
        "sq-ft": 125,
        "price": 150
      },
      { "room-number": 104,
        "use": "office",
        "sq-ft": 150,
        "price": 100
      }
    ],
    "parking": {
      "location": "premium",
      "style": "covered",
      "price": 750
    }
  }
}]

In [66]:
type(data1)

list